version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svaraa_app
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    container_name: svaraa_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: svaraa_jewels
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  appnet:
