services:
  - type: web
    name: svaraa-jewels-backend
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: ${APP_KEY}
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SCOUT_DRIVER
        value: database
