services:
  - type: web
    name: svaraa-jewels-backend
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: ${APP_KEY}
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: svaraa_mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: svaraa_mysql
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: svaraa_mysql
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: svaraa_mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: svaraa_mysql
          property: password
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SCOUT_DRIVER
        value: database

databases:
  - name: svaraa_mysql
    plan: starter
    databaseName: svaraa_jewels
    user: laravel
