[program:svaraa-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/svaraa-jewels/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/svaraa-queue.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
stopwaitsecs=3600

[program:svaraa-queue-mail]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/svaraa-jewels/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --queue=mail
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/svaraa-queue-mail.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=600
